### ISSUE TITLE
Running this action from a private enterprise repository

### ISSUE THREAD

**Issue by jpontdia** [zlatko-ms/envarfiles#44]
I am trying to run this action from a private repository but I get this message:
**Unable to resolve action. Repository not found: zlatko-ms/varfiletoenv**
When running the action from a public repository everything works perfectly

Could you provide me any help to solve this problem?. Thanks in advance

**Comment by zlatko-ms** [comment]
Hi Joaquin, could you please explain your exact context of usage as "private repo" can mean many things ? 

If you reference the action in your workflow code, then the runtime rolling out the workflow and calling envarfiles requires to have access to the public GH zlatko-ms/envarfiles repo. 

If you want to make all of this fuly private, i.e your code can only use your private repo(s), then you need to fork the project in your repo and change the name to reflect the forked name in your repo. 

Any of this help ? If not could you please detail the exact use case ?

**Comment by zlatko-ms** [comment]
Closing as no info on the issue provided
